### ISSUE TITLE
Error while running npm run deploy 

### ISSUE THREAD

**Issue by alexabramkin** [OfficeDev/microsoft-teams-apps-poll#3]
On npm run deploy got the error below:

> poll@1.0.0 deploy /Users/../Documents/p/teamsapptemplates/microsoft-teams-apps-poll-main
> npm run build && npm run zip && upload-action-package -z ./output/ActionPackage.zip -t ./output/ --ld ./output/ --lp poll

> poll@1.0.0 build /Users/../Documents/p/teamsapptemplates/microsoft-teams-apps-poll-main
> webpack --env.mode=prod --env.watch=false

/Users/../Documents/p/teamsapptemplates/microsoft-teams-apps-poll-main/node_modules/copy-webpack-plugin/node_modules/p-limit/index.js:30
		} catch {}
		        ^

SyntaxError: Unexpected token {
    at NativeCompileCache._moduleCompile (/Users/../Documents/p/teamsapptemplates/microsoft-teams-apps-poll-main/node_modules/v8-compile-cache/v8-compile-cache.js:242:18)
    at Module._compile (/Users/../Documents/p/teamsapptemplates/microsoft-teams-apps-poll-main/node_modules/v8-compile-cache/v8-compile-cache.js:186:36)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (/Users/../Documents/p/teamsapptemplates/microsoft-teams-apps-poll-main/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at Object.<anonymous> (/Users/../Documents/p/teamsapptemplates/microsoft-teams-apps-poll-main/node_modules/copy-webpack-plugin/dist/index.js:12:38)
    at Module._compile (/Users/aabramkin/Documents/p/teamsapptemplates/microsoft-teams-apps-poll-main/node_modules/v8-compile-cache/v8-compile-cache.js:194:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (/Users/aabramkin/Documents/p/teamsapptemplates/microsoft-teams-apps-poll-main/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at Object.<anonymous> (/Users/aabramkin/Documents/p/teamsapptemplates/microsoft-teams-apps-poll-main/node_modules/copy-webpack-plugin/dist/cjs.js:3:16)
    at Module._compile (/Users/aabramkin/Documents/p/teamsapptemplates/microsoft-teams-apps-poll-main/node_modules/v8-compile-cache/v8-compile-cache.js:194:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (/Users/aabramkin/Documents/p/teamsapptemplates/microsoft-teams-apps-poll-main/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at Object.<anonymous> (/Users/aabramkin/Documents/p/teamsapptemplates/microsoft-teams-apps-poll-main/webpack.config.js:3:27)
    at Module._compile (/Users/aabramkin/Documents/p/teamsapptemplates/microsoft-teams-apps-poll-main/node_modules/v8-compile-cache/v8-compile-cache.js:194:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! poll@1.0.0 build: `webpack --env.mode=prod --env.watch=false`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the poll@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/aabramkin/.npm/_logs/2020-12-03T23_19_09_102Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! poll@1.0.0 deploy: `npm run build && npm run zip && upload-action-package -z ./output/ActionPackage.zip -t ./output/ --ld ./output/ --lp poll`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the poll@1.0.0 deploy script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/aabramkin/.npm/_logs/2020-12-03T23_19_09_157Z-debug.log

**Comment by alexabramkin** [comment]
Looks like it does not work on node 8. Switched to node 10.20.0. What version of the node we shall be using? Please update documentation to reflect.

**Comment by yogesh-MS** [comment]
Acknowledged. We will update doc with relevant details.
